(define (cons a b)
    (* (expt 2 a) (expt 3 b)))
(define (car c)
    (if (= (gcd c 2) 2)
        (+ 1 (car (/ c 2)))
        0))
(define (cdr c)
    (if (= (gcd c 3) 3)
        (+ 1 (cdr (/ c 3)))
        0))

(define c (cons 0 0)) (car c) (cdr c)
(define c (cons 3 0)) (car c) (cdr c)
(define c (cons 0 3)) (car c) (cdr c)
(define c (cons 2 4)) (car c) (cdr c)
(define c (cons 4 2)) (car c) (cdr c)
